oneschema/sdk

packages/importer/.eslintrc.yml, packages/importer/package.json, packages/importer/src/index.ts, packages/react/.eslintrc.yml, packages/react/package.json, packages/react/src/OneSchemaImporter.tsx, yarn.lock
Adds lint (config pulled from elsewhere, no strong opinions on it). Is not enforced in any way, but, hey, it's there.
Added some checks related checks and fixes
=> Add linting (and related changed)

README.md, packages/angular/projects/oneschema/README.md, packages/angular/projects/oneschema/package.json, packages/importer/README.md, packages/importer/package.json, packages/importer/rollup.config.js, packages/importer/src/index-default.ts, packages/react/README.md, packages/react/package.json
All libs in sync now. Also updating readme's. Also fixing build again (specific entrypoint for JS files so they can use default exporter)
=> Update version numbers to 0.2.0

packages/angular/projects/oneschema/package.json, packages/importer/package.json, packages/importer/src/importer.ts, packages/react/package.json
=> Make iframe transparent

packages/importer/src/importer.ts
Adds a function to retry the init message if launched message has not been received.
=> Retry logic for init message

packages/importer/src/config.ts, yarn.lock
update the typescript file to reflect ui changes
=> Upload Pane UI updates 

CHANGELOG.md, packages/angular/projects/oneschema/package.json, packages/importer/package.json, packages/importer/src/config.ts, packages/importer/src/importer.ts, packages/react/package.json
* Add `fileSizeLimit` to Typescript definiitions for `customizationOverrides
* Add support for `customizationKey` param to specif which customization to use
* Deprecate `launchSession` (use `launch` instead)
=> Add support for `customizationKey` (0.3.1)

CHANGELOG.md, packages/angular/projects/oneschema/package.json, packages/importer/package.json, packages/importer/src/importer.ts, packages/importer/test/index.ts, packages/react/package.json
Webhook success event was erroneously returning `undefined`
=> Webhoook success event

packages/importer/src/config.ts
=> Remove customizationOverrides from session params

CHANGELOG.md, packages/angular/projects/oneschema/package.json, packages/importer/package.json, packages/importer/src/config.ts, packages/importer/src/importer.ts, packages/importer/test/index.ts, packages/react/package.json, packages/react/src/OneSchemaImporter.tsx, yarn.lock
Template Group w/ new message type
=> Add support for template groups

CHANGELOG.md, packages/angular/projects/oneschema/package.json, packages/importer/package.json, packages/importer/src/config.ts, packages/react/package.json, packages/vue/package.json
=> Fix OneSchemaTemplateColumnToUpdate type

CHANGELOG.md, packages/angular/projects/oneschema/package.json, packages/importer/package.json, packages/importer/src/config.ts, packages/react/package.json, packages/vue/package.json
Follow up to https://github.com/oneschema/oneschema/pull/4027
=> Update customization definition

CHANGELOG.md, packages/angular/projects/oneschema/package.json, packages/importer/package.json, packages/importer/src/config.ts, packages/react/package.json, packages/vue/package.json
I decided to not quite do what I said I was going to do here: https://docs.google.com/document/d/1vDwQ1b9OPZsFkakBZ1eBdNw007HUibbXF5PWRe5ghLY/edit#heading=h.o5xyuaigxtda. This is a much more clear interface imo.
=> Advanced mappings

CHANGELOG.md, packages/angular/projects/oneschema/package.json, packages/importer/package.json, packages/importer/src/importer.ts, packages/react/package.json, packages/vue/package.json
add has recieved init listener to importer and make sure to stop retries is oneschema app has recieved init message
=> Stop init retry upon receiving message 

packages/importer/src/importer.ts
Fix issue from PR #74 
- make sure to reset `_hasAppRecievedInitMessage` on importer close
=> Make sure you can re-open sdk

packages/react/src/OneSchemaImporter.tsx
Uggg
@andrewjluo @20michaelz Plz review, merge, and deploy this.
=> Do not run `onRequestClose` on certain errors

packages/vue/test/OneSchemaImporter.vue
Do not subscribe to success/cancel in button handler
=> Fix vue test

packages/importer/src/importer.ts
=> Fix embed misconfigured page

packages/importer/rollup.config.js, packages/importer/src/config.ts, packages/importer/src/importer.ts, packages/importer/test/index.ts, packages/react/src/OneSchemaImporter.tsx, packages/react/test/index.tsx, packages/vue/src/index.ts, packages/vue/src/plugin.ts, packages/vue/test/index.ts
The only logic changes are related to `TemplateGroups`. My editor also made some style changes, which we need unify at some point.
=> importer: Drop TemplateGroups feature

CHANGELOG.md, packages/filefeeds-react/package.json, packages/filefeeds/package.json, packages/importer-angular/angular.json, packages/importer-angular/projects/oneschema/README.md, packages/importer-angular/projects/oneschema/package.json, packages/importer-angular/projects/oneschema/yarn.lock, packages/importer-react/package.json, packages/importer-react/test/index.tsx, packages/importer-vue/package.json, packages/importer-vue/test/index.html, packages/importer/package.json, packages/importer/src/importer.ts, packages/importer/test/index.html, packages/importer/test/index.ts
Add compatibility with OneSchema FileFeeds packages.
Bump versions for 0.6.0 release.
=> packages/importer: Prepare for 0.6.0 release; FF SDK compatiblity

CHANGELOG-filefeeds.md, CHANGELOG.md, packages/filefeeds-react/src/OneSchemaFileFeeds.tsx, packages/filefeeds-react/test/index.tsx, packages/filefeeds/src/events.ts, packages/filefeeds/src/filefeeds.ts, packages/filefeeds/test/index.ts, packages/importer-vue/test/index.ts
The event is triggered via the modal X button (if enabled) or the Cancel
button.
=> filefeeds*: Add cancelled event

packages/filefeeds/src/filefeeds.ts
Merge launch params with params for filefeed launch.
=> merge launch params with params filefeed

packages/filefeeds-react/test/index.tsx, packages/filefeeds/src/events.ts, packages/filefeeds/test/index.html, packages/filefeeds/test/index.ts
Remove session id from event payloads and tests
=> remove session id from event payloads and tests

.vscode/settings.json, packages/filefeeds/package.json, packages/importer/package.json, packages/importer/src/config.ts, packages/importer/src/importer.ts, yarn.lock
=> importer: Drop lodash.merge usage

CHANGELOG-filefeeds.md, packages/filefeeds-react/package.json, packages/filefeeds/package.json
0.5.0 version bump - add session token to filefeeds
=> 0.5.0 version bump

packages/filefeeds-react/src/OneSchemaFileFeeds.tsx, packages/filefeeds-react/test/index.tsx, packages/filefeeds/src/config.ts, packages/filefeeds/src/filefeeds.ts, packages/filefeeds/test/index.html, packages/filefeeds/test/index.ts
add `saveSession` param to toggle autosave behavior
allow save to remove the localstorage token
add `resume token` display on js/react test page for debugging
=> enable toggle of auto-resume capabilities in ff embeds

CHANGELOG-filefeeds.md, packages/filefeeds-react/package.json, packages/filefeeds/package.json
bump `filefeeds` version to `0.5.1`
=> filefeeds 0.5.1 version bump

packages/shared/src/utils.ts
Allow merged to handle undefined objects.
=> allow merged to take an undefined second object

packages/importer/src/config.ts
This change adds Typescript type definitions for the Template column data types.
=> Add type TemplateColumnDataType
